# Generated by Django 3.1.3 on 2020-11-07 15:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommitCodeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_code', models.CharField(default='HIKTest_0102335', max_length=200)),
                ('applicant', models.CharField(max_length=20)),
                ('users', models.CharField(max_length=100)),
                ('code_path', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='结束时间')),
                ('b_expired', models.IntegerField(default=0)),
            ],
        ),
    ]
